export const ProjectStates = {
  NOT_STARTED: 'NOT_STARTED',
  QUEUED: 'QUEUED',
  ANALYZING: 'ANALYZING',
  DESIGNING: 'DESIGNING',
  PLANNING: 'PLANNING',
  WAITING: 'WAITING',
  READY: 'READY',
  BUILDING: 'BUILDING',
  TESTING: 'TESTING',
  REPAIRING: 'REPAIRING',
  CLOUD_BUILDING: 'CLOUD_BUILDING',
  VERIFYING: 'VERIFYING',
  RELEASING: 'RELEASING',
  DOWNLOAD_READY: 'DOWNLOAD_READY',
  COMPLETED: 'COMPLETED',
  BLOCKED: 'BLOCKED',
  FAILED: 'FAILED',
  PAUSED: 'PAUSED'
} as const;

export const AgentStates = {
  IDLE: 'IDLE',
  SELECTING_TASK: 'SELECTING_TASK',
  WAITING: 'WAITING',
  WORKING: 'WORKING',
  REVIEWING: 'REVIEWING',
  TESTING: 'TESTING',
  REPAIRING: 'REPAIRING',
  BLOCKED: 'BLOCKED',
  FAILED: 'FAILED',
  COMPLETED: 'COMPLETED'
} as const;

export const TaskStates = {
  NOT_STARTED: 'NOT_STARTED',
  WAITING: 'WAITING',
  BLOCKED: 'BLOCKED',
  READY: 'READY',
  CLAIMED: 'CLAIMED',
  WORKING: 'WORKING',
  REVIEWING: 'REVIEWING',
  TESTING: 'TESTING',
  FAILED: 'FAILED',
  REPAIRING: 'REPAIRING',
  VERIFIED: 'VERIFIED',
  COMPLETE: 'COMPLETE'
} as const;

export const CloudBuildStages = {
  QUEUED: 'QUEUED',
  CHECKOUT: 'CHECKOUT',
  ENVIRONMENT_SETUP: 'ENVIRONMENT_SETUP',
  DEPENDENCY_RESOLUTION: 'DEPENDENCY_RESOLUTION',
  COMPILING: 'COMPILING',
  UNIT_TESTS: 'UNIT_TESTS',
  INTEGRATION_TESTS: 'INTEGRATION_TESTS',
  STATIC_ANALYSIS: 'STATIC_ANALYSIS',
  SECURITY_CHECKS: 'SECURITY_CHECKS',
  PACKAGING: 'PACKAGING',
  SIGNING: 'SIGNING',
  ARTIFACT_VERIFICATION: 'ARTIFACT_VERIFICATION',
  RELEASE: 'RELEASE'
} as const;

export const FailureRepairStates = {
  FAILURE_DETECTED: 'FAILURE_DETECTED',
  DIAGNOSING: 'DIAGNOSING',
  ROOT_CAUSE_FOUND: 'ROOT_CAUSE_FOUND',
  REPAIR_TASK_CREATED: 'REPAIR_TASK_CREATED',
  AGENT_ASSIGNED: 'AGENT_ASSIGNED',
  REPAIRING: 'REPAIRING',
  RETESTING: 'RETESTING',
  VERIFIED: 'VERIFIED'
} as const;

export const Events = {
  PROJECT_STATUS_CHANGED: 'PROJECT_STATUS_CHANGED',
  TASK_STATUS_CHANGED: 'TASK_STATUS_CHANGED',
  TASK_CREATED: 'TASK_CREATED',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  AGENT_STARTED: 'AGENT_STARTED',
  AGENT_STATUS_CHANGED: 'AGENT_STATUS_CHANGED',
  AGENT_ACTIVITY: 'AGENT_ACTIVITY',
  AGENT_FINISHED: 'AGENT_FINISHED',
  FEATURE_STATUS_CHANGED: 'FEATURE_STATUS_CHANGED',
  TEST_STARTED: 'TEST_STARTED',
  TEST_PROGRESS: 'TEST_PROGRESS',
  TEST_PASSED: 'TEST_PASSED',
  TEST_FAILED: 'TEST_FAILED',
  REPAIR_STARTED: 'REPAIR_STARTED',
  REPAIR_COMPLETED: 'REPAIR_COMPLETED',
  BUILD_STARTED: 'BUILD_STARTED',
  BUILD_STAGE_CHANGED: 'BUILD_STAGE_CHANGED',
  BUILD_OUTPUT: 'BUILD_OUTPUT',
  BUILD_FAILED: 'BUILD_FAILED',
  BUILD_PASSED: 'BUILD_PASSED',
  ARTIFACT_CREATED: 'ARTIFACT_CREATED',
  ARTIFACT_VERIFIED: 'ARTIFACT_VERIFIED',
  RELEASE_CREATED: 'RELEASE_CREATED',
  DOWNLOAD_READY: 'DOWNLOAD_READY'
} as const;

export type ProjectState = typeof ProjectStates[keyof typeof ProjectStates];
export type AgentState = typeof AgentStates[keyof typeof AgentStates];
export type TaskState = typeof TaskStates[keyof typeof TaskStates];
export type CloudBuildStage = typeof CloudBuildStages[keyof typeof CloudBuildStages];
export type FailureRepairState = typeof FailureRepairStates[keyof typeof FailureRepairStates];
